### PR TITLE
Ian calendar

### PR DESCRIPTION
**Pull request by MJOAN**
Pull request for index.html

### CODE REVIEW

**Review by MJOAN — COMMENTED** [review]
Reviewed - ready to merge!

**Comment by HaydenEStern** [comment]
Hi, I'm not able to merge this pull request, @ianstahlp or @MJOAN able to merge?

**Comment by MJOAN** [comment]
So it states conflicts must be resolved due to conflicting files, I can't merge pull request until these have been resolved. I may have to go in from bash/terminal, then checkout and then merge. I can do that at around 5 PM when I will have access to my bash/terminal.  

Step 1: From your project repository, bring in the changes and test.
git fetch origin
git checkout -b ian-calendar origin/ian-calendar
git merge master

Step 2: Merge the changes and update on GitHub.
git checkout master
git merge --no-ff ian-calendar
git push origin master

**Comment by MJOAN** [comment]
Thanks Hayden it's stating conflicts need to be resolved first which I
can't do from Github. Can Ian accept the pull request I initiated? Then I
can approve it for merging.. I believe that is the course of action here..

**Comment by HaydenEStern** [comment]
it's going to be thorny i'm in there trying to merge from the command line right now! but i think i got this

**Comment by MJOAN** [comment]
Okay sweet - no problem, I know Ian must have a copy saved somewhere if the file changes drastically! Thank you again for doing this!

**Pull request merged**
